// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
//using MySql.Data.EntityFrameworkCore.Extensions;

using Employees_MySQL.Models;
using Employees_MySQL.Data;

namespace Employees_MySQL.Data.Migrations
{
    [DbContext(typeof(EmployeesContext))]
    partial class EmployeesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);
                //editar .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmployeesDB.Models.Employees", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();
                    b.Property<string>("Surname")
                        .ValueGeneratedOnAdd();
                    b.Property<string>("Job")
                        .ValueGeneratedOnAdd();
                    b.Property<double>("Salary")
                        .ValueGeneratedOnAdd();

                    //editarb.Property<int?>("Id")
                        //editar.ValueGeneratedOnAdd()
                        //editar .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");
                    b.HasIndex("Id");

                    b.ToTable("Employees");
                });

#pragma warning restore 612, 618
        }
    }
}
